### ISSUE TITLE
Update FreeBSD lang/qore to 0.8.11.1

### ISSUE THREAD

**Issue by 357r4bd** [qorelanguage/qore-freebsd-ports#1]
Language support on FreeBSD is behind at 0.8.8; it needs to be updated.

**Comment by 357r4bd** [comment]
I'll do it. =)

**Comment by 357r4bd** [comment]
Work is ongoing in https://github.com/qorelanguage/qore-freebsd-ports/tree/Issue-1-update-to-0.8.11.1

I need to deal with the patch they added that is not applying cleanly.

**Comment by 357r4bd** [comment]
Ok, I'll be doing a couple of sanity checks, but I think it's ready to get submitted as an update...this evening or tomorrow it should be done.

**Comment by davidnich** [comment]
sounds great, Brett, thanks!

**Comment by 357r4bd** [comment]
Ok, finally got around to submitting.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=202230

I'll see it through to completion.

**Comment by 357r4bd** [comment]
I just sent an email follow up for the above issue, not sure why it's taking so long to get my Port update reviewed by the FreeBSD Port folks.

**Comment by 357r4bd** [comment]
It's been updated! 

http://www.freshports.org/lang/qore/

**Comment by davidnich** [comment]
ok great, thanks Brett!  We have a really big release in the works for 0.8.12 - will take a while to get ready though at the current rate...
